ALTER TABLE epicrisis ADD COLUMN version_clinica INTEGER NOT NULL DEFAULT 1;
ALTER TABLE epicrisis ADD COLUMN estado_registro VARCHAR(20) NOT NULL DEFAULT 'VIGENTE';
ALTER TABLE epicrisis ADD COLUMN fecha_ultima_rectificacion TIMESTAMP WITH TIME ZONE;

ALTER TABLE tratamientos ADD COLUMN version_clinica INTEGER NOT NULL DEFAULT 1;
ALTER TABLE tratamientos ADD COLUMN estado_registro VARCHAR(20) NOT NULL DEFAULT 'VIGENTE';
ALTER TABLE tratamientos ADD COLUMN fecha_ultima_rectificacion TIMESTAMP WITH TIME ZONE;

ALTER TABLE sesiones_tratamiento ADD COLUMN version_clinica INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sesiones_tratamiento ADD COLUMN estado_registro VARCHAR(20) NOT NULL DEFAULT 'VIGENTE';
ALTER TABLE sesiones_tratamiento ADD COLUMN fecha_ultima_rectificacion TIMESTAMP WITH TIME ZONE;

ALTER TABLE epicrisis DROP CONSTRAINT fk_epicrisis_paciente;
ALTER TABLE epicrisis ADD CONSTRAINT fk_epicrisis_paciente
    FOREIGN KEY (id_paciente) REFERENCES pacientes (id);

ALTER TABLE tratamientos DROP CONSTRAINT fk_tratamiento_paciente;
ALTER TABLE tratamientos ADD CONSTRAINT fk_tratamiento_paciente
    FOREIGN KEY (id_paciente) REFERENCES pacientes (id);

ALTER TABLE sesiones_tratamiento DROP CONSTRAINT fk_sesion_tratamiento;
ALTER TABLE sesiones_tratamiento ADD CONSTRAINT fk_sesion_tratamiento
    FOREIGN KEY (id_tratamiento) REFERENCES tratamientos (id);

CREATE TABLE auditoria_rectificaciones_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_registro VARCHAR(20) NOT NULL,
    id_registro BIGINT NOT NULL,
    id_paciente BIGINT NOT NULL,
    id_profesional BIGINT NOT NULL,
    nombre_profesional VARCHAR(200),
    matricula_profesional VARCHAR(100),
    version_anterior INTEGER NOT NULL,
    version_nueva INTEGER NOT NULL,
    tipo_motivo VARCHAR(40) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    conservar_hasta TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_origen VARCHAR(64) NOT NULL,
    equipo VARCHAR(500) NOT NULL,
    id_sesion VARCHAR(128),
    id_solicitud VARCHAR(128) NOT NULL,
    antes_cifrado BYTEA NOT NULL,
    antes_iv BYTEA NOT NULL,
    despues_cifrado BYTEA NOT NULL,
    despues_iv BYTEA NOT NULL,
    hash_antes VARCHAR(64) NOT NULL,
    hash_despues VARCHAR(64) NOT NULL,
    hash_anterior_cadena VARCHAR(64),
    hash_cadena VARCHAR(64) NOT NULL,
    CONSTRAINT chk_auditoria_versiones CHECK (version_anterior > 0 AND version_nueva = version_anterior + 1),
    CONSTRAINT uq_auditoria_registro_version UNIQUE (tipo_registro, id_registro, version_nueva)
);

CREATE INDEX idx_auditoria_propietario_registro
    ON auditoria_rectificaciones_clinicas (id_profesional, id_paciente, tipo_registro, id_registro, id);
