CREATE TABLE exportaciones_historia_clinica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_profesional BIGINT NOT NULL,
    motivo VARCHAR(40) NOT NULL,
    detalle_motivo VARCHAR(500),
    formato VARCHAR(10) NOT NULL,
    fecha_hora_exportacion TIMESTAMP WITH TIME ZONE NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    hash_archivo VARCHAR(64) NOT NULL,
    CONSTRAINT fk_exportacion_historia_paciente FOREIGN KEY (id_paciente) REFERENCES pacientes (id)
);

CREATE INDEX idx_exportacion_historia_profesional_paciente
    ON exportaciones_historia_clinica (id_profesional, id_paciente, fecha_hora_exportacion);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    id_profesional BIGINT NOT NULL,
    id_paciente BIGINT NOT NULL,
    formato VARCHAR(10),
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    resultado VARCHAR(10) NOT NULL
);

CREATE INDEX idx_audit_log_exportacion
    ON audit_log (action, id_profesional, id_paciente, fecha_hora);
