CREATE TABLE fichas_medicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional BIGINT NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_fichas_medicas_id_profesional ON fichas_medicas (id_profesional);

CREATE TABLE detalles_ficha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ficha_medica BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    orden INTEGER NOT NULL,
    CONSTRAINT fk_detalles_ficha_ficha_medica
        FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas (id) ON DELETE CASCADE,
    CONSTRAINT chk_detalles_ficha_orden CHECK (orden >= 0)
);

CREATE INDEX idx_detalles_ficha_id_ficha ON detalles_ficha (id_ficha_medica);

CREATE TABLE campos_para_llenar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detalle_ficha BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500),
    orden INTEGER NOT NULL,
    CONSTRAINT fk_campos_para_llenar_detalle
        FOREIGN KEY (id_detalle_ficha) REFERENCES detalles_ficha (id) ON DELETE CASCADE,
    CONSTRAINT chk_campos_para_llenar_orden CHECK (orden >= 0)
);

CREATE INDEX idx_campos_para_llenar_id_detalle_ficha ON campos_para_llenar (id_detalle_ficha);

CREATE TABLE opciones_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campo_para_llenar BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    tipo_opcion VARCHAR(20) NOT NULL,
    descripcion VARCHAR(500),
    orden INTEGER NOT NULL,
    grupo_exclusion VARCHAR(80),
    CONSTRAINT fk_opciones_campo_campo
        FOREIGN KEY (id_campo_para_llenar) REFERENCES campos_para_llenar (id) ON DELETE CASCADE,
    CONSTRAINT chk_opciones_campo_orden CHECK (orden >= 0),
    CONSTRAINT chk_opciones_campo_tipo CHECK (tipo_opcion IN ('SELECCION', 'ENTRADA'))
);

CREATE INDEX idx_opciones_campo_id_campo_para_llenar ON opciones_campo (id_campo_para_llenar);
