CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    dni VARCHAR(12) NOT NULL,
    telefono VARCHAR(30),
    fecha_nacimiento DATE NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_pacientes_profesional_dni UNIQUE (id_profesional, dni),
    CONSTRAINT chk_pacientes_sexo CHECK (sexo IN ('FEMENINO', 'MASCULINO', 'OTRO', 'NO_ESPECIFICA'))
);

CREATE INDEX idx_pacientes_id_profesional ON pacientes (id_profesional);
CREATE INDEX idx_pacientes_profesional_apellido ON pacientes (id_profesional, apellido, nombre);
