CREATE TABLE fichas_paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_ficha_medica BIGINT NOT NULL,
    fecha_asignacion TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_fichas_paciente_paciente FOREIGN KEY (id_paciente) REFERENCES pacientes (id) ON DELETE CASCADE,
    CONSTRAINT fk_fichas_paciente_ficha FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas (id)
);

CREATE TABLE respuestas_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ficha_paciente BIGINT NOT NULL,
    id_opcion_campo BIGINT NOT NULL,
    valor VARCHAR(1000),
    seleccionada BOOLEAN,
    CONSTRAINT uk_respuestas_ficha_opcion UNIQUE (id_ficha_paciente, id_opcion_campo),
    CONSTRAINT fk_respuestas_ficha_paciente FOREIGN KEY (id_ficha_paciente) REFERENCES fichas_paciente (id) ON DELETE CASCADE,
    CONSTRAINT fk_respuestas_opcion FOREIGN KEY (id_opcion_campo) REFERENCES opciones_campo (id)
);

CREATE INDEX idx_fichas_paciente_ficha ON fichas_paciente (id_ficha_medica);
CREATE INDEX idx_fichas_paciente_paciente ON fichas_paciente (id_paciente);
CREATE INDEX idx_respuestas_ficha_paciente ON respuestas_campo (id_ficha_paciente);
