CREATE TABLE fichas_paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_plantilla_origen BIGINT NOT NULL,
    nombre_ficha VARCHAR(120) NOT NULL,
    descripcion_ficha VARCHAR(500),
    version_plantilla BIGINT NOT NULL,
    fecha_asignacion TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_fichas_paciente_paciente FOREIGN KEY (id_paciente) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE respuestas_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ficha_paciente BIGINT NOT NULL,
    id_opcion_origen BIGINT NOT NULL,
    titulo_detalle VARCHAR(150) NOT NULL,
    descripcion_detalle VARCHAR(500),
    orden_detalle INTEGER NOT NULL,
    titulo_campo VARCHAR(150) NOT NULL,
    descripcion_campo VARCHAR(500),
    orden_campo INTEGER NOT NULL,
    permite_seleccion_multiple BOOLEAN NOT NULL,
    titulo_opcion VARCHAR(150),
    tipo_opcion VARCHAR(20) NOT NULL,
    descripcion_opcion VARCHAR(500),
    orden_opcion INTEGER NOT NULL,
    grupo_exclusion VARCHAR(80),
    valor VARCHAR(1000),
    seleccionada BOOLEAN,
    CONSTRAINT uk_respuestas_ficha_opcion UNIQUE (id_ficha_paciente, id_opcion_origen),
    CONSTRAINT fk_respuestas_ficha_paciente FOREIGN KEY (id_ficha_paciente) REFERENCES fichas_paciente (id) ON DELETE CASCADE
);

CREATE INDEX idx_fichas_paciente_plantilla_origen ON fichas_paciente (id_plantilla_origen);
CREATE INDEX idx_fichas_paciente_paciente ON fichas_paciente (id_paciente);
CREATE INDEX idx_respuestas_ficha_paciente ON respuestas_campo (id_ficha_paciente);
