CREATE TABLE epicrisis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    observaciones VARCHAR(5000) NOT NULL,
    CONSTRAINT fk_epicrisis_paciente FOREIGN KEY (id_paciente) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE INDEX idx_epicrisis_paciente_fecha ON epicrisis (id_paciente, fecha_hora DESC);
